server:
  port: 8080
spring:
  application:
    name: msc-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #defaultZone: http://localhost:7001/eureka
  #配置服务实例ID
  instance:
    instance-id: consumer8080
    #显示服务IP地址
    prefer-ip-address: true
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
  ConnectionTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控那个接口
    com.daop.msc.order.feign.service.PaymentFeignService: debug