server:
  port: 9527
spring:
  application:
    name: msc-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh               #路由的ID没有唯一要求，建议配合服务名
          #uri: http://localhost:8001     #匹配后提供的服务路由地址
          uri: lb://MSC-PAYMENT-SERVICE   #匹配后提供的服务名
          predicates:
            - Path=/payment/get/**        #断言，路径匹配后的进行路由

        - id: payment_routh               #路由的ID没有唯一要求，建议配合服务名
          #uri: http://localhost:8001     #匹配后提供的服务路由地址
          uri: lb://MSC-PAYMENT-SERVICE   #匹配后提供的服务名
          predicates:
            - Path=/payment/lb/**         #断言，路径匹配后的进行路由
            #- After=2020-10-22T14:20:00.000+08:00[Asia/Shanghai]
            #- Cookie=username,ddp
            #- Header=X-Request-Id, \d+
eureka:
  instance:
    hostname: msc-gateway-9527
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
