server:
  port: 8080
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9000
        port: 8719

service-url:
  nacos-user-service: http://nacos-payment-provider
