server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1111 #通过nginx将服务注册到注册中心
      #配置Nacos服务地址
        #server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"