server:
  port: 8041
spring:
  application:
    name: msc-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel Dashboard地址
        dashboard: localhost:9000
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"