server:
  port: 8080
spring:
  application:
    name: msc-order-hystrix-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
  #配置服务实例ID
  instance:
    instance-id: consumer-hystrix-8080
    #显示服务IP地址
    prefer-ip-address: true
#开启Hystrix服务降级熔断支持
feign:
  hystrix:
    enabled: true